spring:
  application:
    name: reporting-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:h2:mem:reportingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085
  servlet:
    context-path: /api

# Service URLs (for calling other services)
services:
  student-profile-url: http://localhost:8081/api
  course-enrolment-url: http://localhost:8082/api
  library-url: http://localhost:8084/api

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always